#!/bin/sh

set -x

seconds=2400
sed_script="/^$seconds s/q"

for pages in $(seq 32 -1 1); do
  for family in tcp unix; do
    for io in splicetee recvsend; do
      ./echo-server "$io" "$family" "$pages" | sed "$sed_script"
      rm -rf /tmp/echo-server-*
      mv log "$io-$family-$pages.log"
    done
  done
done


